import re
f = open('sql/05_views_indexes_roles.sql', 'r', encoding='utf-8')
content = f.read()
f.close()
content = re.sub(r'<<<<<<< HEAD\n', '', content)
content = re.sub(r'=======\n', '', content)
content = re.sub(r'>>>>>>> origin/feature/jenn\n', '', content)
f = open('sql/05_views_indexes_roles.sql', 'w', encoding='utf-8')
f.write(content)
f.close()
print('OK - lines:', len(content.split('\n')))
